name: Run Tests

on:
  push:
    branches:
      - jorge

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install pytest pytest-html pytest-timeout

    - name: Run tests
      run: |
        pytest --html=report.html

    - name: Upload test report
      uses: actions/upload-artifact@v4.3.3
      with:
        name: test-reports
        path: report.html
